import Header from "@/components/Header";
import LeftBar from "@/components/LeftBar";
import Footer from "@/components/Footer";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Muhammed-Trello',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<html lang="en">
  <body className={`${inter.className} flex flex-col min-h-screen`}>
    <Header />
    <div className="flex-grow flex">
      <LeftBar />
      <main className="p-8 ml-64">
        {children}
      </main>
    </div>
    {/* <Footer />  */}
  </body>
</html>
  );
}
